spring:

    # JSP 파일을 사용하기 위한 설정
    mvc:
        view:
            prefix: /view/
            suffix: .jsp
    social: 
        facebook: 
            appId: 1687598368235887
            appSecret: 6cedf9fad691b370013d001c793907c4

    # DB를 사용하기 위한 설정
    datasource:

        platform: oracle
        #url: jdbc:oracle:thin:@//orlc.clvk5kokhwjz.ap-northeast-2.rds.amazonaws.com:1521/orcl
        #driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:log4jdbc:oracle:thin:@//orlc.clvk5kokhwjz.ap-northeast-2.rds.amazonaws.com:1521/orcl
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: dodo
        password: 1234qwer
        dbcp:
            max-active: 3
        tomcat:
            max-active: 3
            

    # wabjar 버전생략 locator를 위한 설정
    # ..인데 왜 안될까
    resources.chain.enabled: true
    
    # HTTP encoding (HttpEncodingProperties)
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    
    # MULTIPART (MultipartProperties)
        multipart:
            enabled: true
            file-size-threshold: 500MB
            max-file-size: 5Mb
            max-request-size: 10Mb
            resolve-lazily: false
            
---

spring:
    profiles: product
    
#Spring Boot App 시작 포트 설정
server.port: 80
---

spring:
    profiles: development
    
#Spring Boot App 시작 포트 설정
server.port: 80