spring:

    # JSP 파일을 사용하기 위한 설정
    mvc:
        view:
            prefix: /view/
            suffix: .jsp
    social: 
        facebook: 
            appId: 1687598368235887
            appSecret: 6cedf9fad691b370013d001c793907c4

    # DB를 사용하기 위한 설정
    datasource:
        url: jdbc:oracle:thin:@orlc.clvk5kokhwjz.ap-northeast-2.rds.amazonaws.com:1521
        username: dodo
        password: 1234qwer
        driver-class-name: oracle.jdbc.OracleDriver

#Spring Boot App 시작 포트 설정
server.port: 80