
function load_card() {
    var data = ([
        {
            "id": 1,
            "code": "NOBL303330",
            "name": "카트린 드 메디시스",
            "img": "/img/cards/hero_B3G3R3.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [0, 3, 3, 3, 0]
        },
        {
            "id": 2,
            "code": "NOBL333003",
            "name": "오스트리아의 엘리자베트",
            "img": "/img/cards/hero_B3W3K3.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [3, 3, 0, 0, 3]
        },
        {
            "id": 3,
            "code": "NOBL340004",
            "name": "이사벨 1세",
            "img": "/img/cards/hero_W4K4.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [4, 0, 0, 0, 4]
        },
        {
            "id": 4,
            "code": "NOBL344000",
            "name": "니콜로 마키아벨리",
            "img": "/img/cards/hero_B4W4.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [4, 4, 0, 0, 0]
        },
        {
            "id": 5,
            "code": "NOBL304400",
            "name": "쉴레이만 대제",
            "img": "/img/cards/hero_G4B4.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [0, 4, 4, 0, 0]
        },
        {
            "id": 6,
            "code": "NOBL333300",
            "name": "안느 드 브르타뉴",
            "img": "/img/cards/hero_B3W3G3.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [3, 3, 3, 0, 0]
        },
        {
            "id": 7,
            "code": "NOBL330033",
            "name": "샤를 5세",
            "img": "/img/cards/hero_K3W3R3.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [3, 0, 0, 3, 3]
        },
        {
            "id": 8,
            "code": "NOBL300333",
            "name": "프랑수아 1세",
            "img": "/img/cards/hero_K3G3R3.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [0, 0, 3, 3, 3]
        },
        {
            "id": 9,
            "code": "NOBL300044",
            "name": "헨리 8세",
            "img": "/img/cards/hero_R4K4.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [0, 0, 0, 4, 4]
        },
        {
            "id": 10,
            "code": "NOBL300440",
            "name": "메리 스튜어트",
            "img": "/img/cards/hero_G4R4.png",
            "info": "",
            "yield": 6,
            "lv": 4,
            "score": 3,
            "price": [0, 0, 4, 4, 0]
        },
        {
            "id": 11,
            "code": "CD1K011110",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_W1B1G1R1.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 0,
            "price": [1, 1, 1, 1, 0]
        },
        {
            "id": 12,
            "code": "CD1K012110",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_W1B2G1R1.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 0,
            "price": [1, 2, 1, 1, 0]
        },
        {
            "id": 13,
            "code": "CD1K022010",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_W2B2R1.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 0,
            "price": [2, 2, 0, 1, 0]
        },
        {
            "id": 14,
            "code": "CD1K000131",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_G1R3K1.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 0,
            "price": [0, 0, 1, 3, 1]
        },
        {
            "id": 15,
            "code": "CD1K000210",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_G2R1.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 0,
            "price": [0, 0, 2, 1, 0]
        },
        {
            "id": 16,
            "code": "CD1K020200",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_W2G2.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 0,
            "price": [2, 0, 2, 0, 0]
        },
        {
            "id": 17,
            "code": "CD1K000300",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_G3.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 0,
            "price": [0, 0, 3, 0, 0]
        },
        {
            "id": 18,
            "code": "CD1K104000",
            "name": "mine (black)",
            "img": "/img/cards/lev1_Black_B4.png",
            "info": "",
            "yield": 5,
            "lv": 1,
            "score": 1,
            "price": [0, 4, 0, 0, 0]
        },
        {
            "id": 19,
            "code": "CD1B010111",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_W1G1R1K1.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 0,
            "price": [1, 0, 1, 1, 1]
        },
        {
            "id": 20,
            "code": "CD1B010121",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_W1G1R2K1.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 0,
            "price": [1, 0, 1, 2, 1]
        },
        {
            "id": 21,
            "code": "CD1B010220",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_W1G2R2.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 0,
            "price": [1, 0, 2, 2, 0]
        },
        {
            "id": 22,
            "code": "CD1B001310",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_B1G3R1.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 0,
            "price": [0, 1, 3, 1, 0]
        },
        {
            "id": 23,
            "code": "CD1B010002",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_W1K2.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 0,
            "price": [1, 0, 0, 0, 2]
        },
        {
            "id": 24,
            "code": "CD1B000202",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_G2K2.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 0,
            "price": [0, 0, 2, 0, 2]
        },
        {
            "id": 25,
            "code": "CD1B000003",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_K3.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 0,
            "price": [0, 0, 0, 0, 3]
        },
        {
            "id": 26,
            "code": "CD1B100040",
            "name": "mine (blue)",
            "img": "/img/cards/lev1_Blue_R4.png",
            "info": "",
            "yield": 2,
            "lv": 1,
            "score": 1,
            "price": [0, 0, 0, 4, 0]
        },
        {
            "id": 27,
            "code": "CD1W001111",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_B1G1R1K1.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 0,
            "price": [0, 1, 1, 1, 1]
        },
        {
            "id": 28,
            "code": "CD1W001211",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_W1B1G2R1.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 0,
            "price": [0, 1, 2, 1, 1]
        },
        {
            "id": 29,
            "code": "CD1W002201",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_B2G2K1.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 0,
            "price": [0, 2, 2, 0, 1]
        },
        {
            "id": 30,
            "code": "CD1W031001",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_W3B1K1.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 0,
            "price": [3, 1, 0, 0, 1]
        },
        {
            "id": 31,
            "code": "CD1W000021",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_R2K1.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 0,
            "price": [0, 0, 0, 2, 1]
        },
        {
            "id": 32,
            "code": "CD1W002002",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_B2K2.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 0,
            "price": [0, 2, 0, 0, 2]
        },
        {
            "id": 33,
            "code": "CD1W003000",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_B3.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 0,
            "price": [0, 3, 0, 0, 0]
        },
        {
            "id": 34,
            "code": "CD1W100400",
            "name": "mine (white)",
            "img": "/img/cards/lev1_White_G4.png",
            "info": "",
            "yield": 1,
            "lv": 1,
            "score": 1,
            "price": [0, 0, 4, 0, 0]
        },
        {
            "id": 35,
            "code": "CD1G011011",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_W1B1R1K1.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 0,
            "price": [1, 1, 0, 1, 1]
        },
        {
            "id": 36,
            "code": "CD1G011012",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_W1B1R1K2.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 0,
            "price": [1, 1, 0, 1, 2]
        },
        {
            "id": 37,
            "code": "CD1G001022",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_B1R2K2.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 0,
            "price": [0, 1, 0, 2, 2]
        },
        {
            "id": 38,
            "code": "CD1G013100",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_W1B3G1.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 0,
            "price": [1, 3, 1, 0, 0]
        },
        {
            "id": 39,
            "code": "CD1G021000",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_W2B1.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 0,
            "price": [2, 1, 0, 0, 0]
        },
        {
            "id": 40,
            "code": "CD1G002020",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_B2R2.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 0,
            "price": [0, 2, 0, 2, 0]
        },
        {
            "id": 41,
            "code": "CD1G000030",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_R3.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 0,
            "price": [0, 0, 0, 3, 0]
        },
        {
            "id": 42,
            "code": "CD1G100004",
            "name": "mine (green)",
            "img": "/img/cards/lev1_Green_K4.png",
            "info": "",
            "yield": 3,
            "lv": 1,
            "score": 1,
            "price": [0, 0, 0, 0, 4]
        },
        {
            "id": 43,
            "code": "CD1R011101",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_W1B1G1K1.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 0,
            "price": [1, 1, 1, 0, 1]
        },
        {
            "id": 44,
            "code": "CD1R021101",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_W2B1G1K1.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 0,
            "price": [2, 1, 1, 0, 1]
        },
        {
            "id": 45,
            "code": "CD1R020102",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_W2G1K2.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 0,
            "price": [2, 0, 1, 0, 2]
        },
        {
            "id": 46,
            "code": "CD1R010013",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_W1R1K3.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 0,
            "price": [1, 0, 0, 1, 3]
        },
        {
            "id": 47,
            "code": "CD1R002100",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_B2G1.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 0,
            "price": [0, 2, 1, 0, 0]
        },
        {
            "id": 48,
            "code": "CD1R020020",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_W2R2.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 0,
            "price": [2, 0, 0, 2, 0]
        },
        {
            "id": 49,
            "code": "CD1R030000",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_W3.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 0,
            "price": [3, 0, 0, 0, 0]
        },
        {
            "id": 50,
            "code": "CD1R140000",
            "name": "mine (red)",
            "img": "/img/cards/lev1_Red_W4.png",
            "info": "",
            "yield": 4,
            "lv": 1,
            "score": 1,
            "price": [4, 0, 0, 0, 0]
        },
        {
            "id": 51,
            "code": "CD2K132200",
            "name": "camels",
            "img": "/img/cards/lev2_Black_W3B2G2.png",
            "info": "",
            "yield": 5,
            "lv": 2,
            "score": 1,
            "price": [3, 2, 2, 0, 0]
        },
        {
            "id": 52,
            "code": "CD2K130302",
            "name": "camels",
            "img": "/img/cards/lev2_Black_W3G3K2.png",
            "info": "",
            "yield": 5,
            "lv": 2,
            "score": 1,
            "price": [3, 0, 3, 0, 2]
        },
        {
            "id": 53,
            "code": "CD2K201420",
            "name": "camels",
            "img": "/img/cards/lev2_Black_B1G4R2.png",
            "info": "",
            "yield": 5,
            "lv": 2,
            "score": 2,
            "price": [0, 1, 4, 2, 0]
        },
        {
            "id": 55,
            "code": "CD2K250000",
            "name": "lapidary (black)",
            "img": "/img/cards/lev2_Black_W5.png",
            "info": "",
            "yield": 5,
            "lv": 2,
            "score": 2,
            "price": [5, 0, 0, 0, 0]
        },
        {
            "id": 56,
            "code": "CD2K300006",
            "name": "lapidary (black)",
            "img": "/img/cards/lev2_Black_K6.png",
            "info": "",
            "yield": 5,
            "lv": 2,
            "score": 3,
            "price": [0, 0, 0, 0, 6]
        },
        {
            "id": 57,
            "code": "CD2B102230",
            "name": "elephants",
            "img": "/img/cards/lev2_Blue_B2G2R3.png",
            "info": "",
            "yield": 2,
            "lv": 2,
            "score": 1,
            "price": [0, 2, 2, 3, 0]
        },
        {
            "id": 58,
            "code": "CD2B102303",
            "name": "elephants",
            "img": "/img/cards/lev2_Blue_B2G3K3.png",
            "info": "",
            "yield": 2,
            "lv": 2,
            "score": 1,
            "price": [0, 2, 3, 0, 3]
        },
        {
            "id": 59,
            "code": "CD2B253000",
            "name": "elephants",
            "img": "/img/cards/lev2_Blue_W5B3.png",
            "info": "",
            "yield": 2,
            "lv": 2,
            "score": 2,
            "price": [5, 3, 0, 0, 0]
        },
        {
            "id": 60,
            "code": "CD2B220014",
            "name": "lapidary (blue)",
            "img": "/img/cards/lev2_Blue_W2R1K4.png",
            "info": "",
            "yield": 2,
            "lv": 2,
            "score": 2,
            "price": [2, 0, 0, 1, 4]
        },
        {
            "id": 61,
            "code": "CD2B205000",
            "name": "lapidary (blue)",
            "img": "/img/cards/lev2_Blue_B5.png",
            "info": "",
            "yield": 2,
            "lv": 2,
            "score": 2,
            "price": [0, 5, 0, 0, 0]
        },
        {
            "id": 63,
            "code": "CD2W100322",
            "name": "people in snow",
            "img": "/img/cards/lev2_White_G3R2K2.png",
            "info": "",
            "yield": 1,
            "lv": 2,
            "score": 1,
            "price": [0, 0, 3, 2, 2]
        },
        {
            "id": 64,
            "code": "CD2W123030",
            "name": "people in snow",
            "img": "/img/cards/lev2_White_W2B3R3.png",
            "info": "",
            "yield": 1,
            "lv": 2,
            "score": 1,
            "price": [2, 3, 0, 3, 0]
        },
        {
            "id": 65,
            "code": "CD2W200142",
            "name": "people in snow",
            "img": "/img/cards/lev2_White_G1R4K2.png",
            "info": "",
            "yield": 1,
            "lv": 2,
            "score": 2,
            "price": [0, 0, 1, 4, 2]
        },
        {
            "id": 66,
            "code": "CD2W200053",
            "name": "lapidary (white)",
            "img": "/img/cards/lev2_White_R5K3.png",
            "info": "",
            "yield": 1,
            "lv": 2,
            "score": 2,
            "price": [0, 0, 0, 5, 3]
        },
        {
            "id": 67,
            "code": "CD2W200050",
            "name": "lapidary (white)",
            "img": "/img/cards/lev2_White_R5.png",
            "info": "",
            "yield": 1,
            "lv": 2,
            "score": 2,
            "price": [0, 0, 0, 5, 0]
        },
        {
            "id": 68,
            "code": "CD2W360000",
            "name": "lapidary (white)",
            "img": "/img/cards/lev2_White_W6.png",
            "info": "",
            "yield": 1,
            "lv": 2,
            "score": 3,
            "price": [6, 0, 0, 0, 0]
        },
        {
            "id": 69,
            "code": "CD2G130230",
            "name": "guy (green)",
            "img": "/img/cards/lev2_Green_W3G2R3.png",
            "info": "",
            "yield": 3,
            "lv": 2,
            "score": 1,
            "price": [3, 0, 2, 3, 0]
        },
        {
            "id": 70,
            "code": "CD2G123002",
            "name": "guy (green)",
            "img": "/img/cards/lev2_Green_W2B3K2.png",
            "info": "",
            "yield": 3,
            "lv": 2,
            "score": 1,
            "price": [2, 3, 0, 0, 2]
        },
        {
            "id": 71,
            "code": "CD2G242001",
            "name": "guy (green)",
            "img": "/img/cards/lev2_Green_W4B2K1.png",
            "info": "",
            "yield": 3,
            "lv": 2,
            "score": 2,
            "price": [4, 2, 0, 0, 1]
        },
        {
            "id": 72,
            "code": "CD2G205300",
            "name": "carrack",
            "img": "/img/cards/lev2_Green_B5G3.png",
            "info": "",
            "yield": 3,
            "lv": 2,
            "score": 2,
            "price": [0, 5, 3, 0, 0]
        },
        {
            "id": 73,
            "code": "CD2G200500",
            "name": "carrack",
            "img": "/img/cards/lev2_Green_G5.png",
            "info": "",
            "yield": 3,
            "lv": 2,
            "score": 2,
            "price": [0, 0, 5, 0, 0]
        },
        {
            "id": 74,
            "code": "CD2G300600",
            "name": "carrack",
            "img": "/img/cards/lev2_Green_G6.png",
            "info": "",
            "yield": 3,
            "lv": 2,
            "score": 3,
            "price": [0, 0, 6, 0, 0]
        },
        {
            "id": 75,
            "code": "CD2R120023",
            "name": "felucca",
            "img": "/img/cards/lev2_Red_W2R2K3.png",
            "info": "",
            "yield": 4,
            "lv": 2,
            "score": 1,
            "price": [2, 0, 0, 2, 3]
        },
        {
            "id": 76,
            "code": "CD2R103023",
            "name": "felucca",
            "img": "/img/cards/lev2_Red_B3R2K3.png",
            "info": "",
            "yield": 4,
            "lv": 2,
            "score": 1,
            "price": [0, 3, 0, 2, 3]
        },
        {
            "id": 77,
            "code": "CD2R214200",
            "name": "felucca",
            "img": "/img/cards/lev2_Red_W1B4G2.png",
            "info": "",
            "yield": 4,
            "lv": 2,
            "score": 2,
            "price": [1, 4, 2, 0, 0]
        },
        {
            "id": 78,
            "code": "CD2R230005",
            "name": "lapidary (red)",
            "img": "/img/cards/lev2_Red_W3K5.png",
            "info": "",
            "yield": 4,
            "lv": 2,
            "score": 2,
            "price": [3, 0, 0, 0, 5]
        },
        {
            "id": 79,
            "code": "CD2R200005",
            "name": "lapidary (red)",
            "img": "/img/cards/lev2_Red_K5.png",
            "info": "",
            "yield": 4,
            "lv": 2,
            "score": 2,
            "price": [0, 0, 0, 0, 5]
        },
        {
            "id": 80,
            "code": "CD2R300060",
            "name": "lapidary (red)",
            "img": "/img/cards/lev2_Red_R6.png",
            "info": "",
            "yield": 4,
            "lv": 2,
            "score": 3,
            "price": [0, 0, 0, 6, 0]
        },
        {
            "id": 81,
            "code": "CD3K333530",
            "name": "street1",
            "img": "/img/cards/lev3_Black_W3B3G5R3.png",
            "info": "",
            "yield": 5,
            "lv": 3,
            "score": 3,
            "price": [3, 3, 5, 3, 0]
        },
        {
            "id": 82,
            "code": "CD3K400070",
            "name": "street2",
            "img": "/img/cards/lev3_Black_R7.png",
            "info": "",
            "yield": 5,
            "lv": 3,
            "score": 4,
            "price": [0, 0, 0, 7, 0]
        },
        {
            "id": 83,
            "code": "CD3K400363",
            "name": "street2",
            "img": "/img/cards/lev3_Black_G3R6K3.png",
            "info": "",
            "yield": 5,
            "lv": 3,
            "score": 4,
            "price": [0, 0, 3, 6, 3]
        },
        {
            "id": 84,
            "code": "CD3K500073",
            "name": "street1",
            "img": "/img/cards/lev3_Black_R7K3.png",
            "info": "",
            "yield": 5,
            "lv": 3,
            "score": 5,
            "price": [0, 0, 0, 7, 3]
        },
        {
            "id": 85,
            "code": "CD3B330335",
            "name": "Venice",
            "img": "/img/cards/lev3_Blue_W3G3R3K5.png",
            "info": "",
            "yield": 2,
            "lv": 3,
            "score": 3,
            "price": [3, 0, 3, 3, 5]
        },
        {
            "id": 86,
            "code": "CD3B470000",
            "name": "Venice",
            "img": "/img/cards/lev3_Blue_W7.png",
            "info": "",
            "yield": 2,
            "lv": 3,
            "score": 4,
            "price": [7, 0, 0, 0, 0]
        },
        {
            "id": 87,
            "code": "CD3B463003",
            "name": "diamant shop",
            "img": "/img/cards/lev3_Blue_W6B3K3.png",
            "info": "",
            "yield": 2,
            "lv": 3,
            "score": 4,
            "price": [6, 3, 0, 0, 3]
        },
        {
            "id": 88,
            "code": "CD3B573000",
            "name": "diamant shop",
            "img": "/img/cards/lev3_Blue_W7B3.png",
            "info": "",
            "yield": 2,
            "lv": 3,
            "score": 5,
            "price": [7, 3, 0, 0, 0]
        },
        {
            "id": 89,
            "code": "CD3W303353",
            "name": "building (white)",
            "img": "/img/cards/lev3_White_B3G3R5K3.png",
            "info": "",
            "yield": 1,
            "lv": 3,
            "score": 3,
            "price": [0, 3, 3, 5, 3]
        },
        {
            "id": 90,
            "code": "CD3W400007",
            "name": "Gioielleria",
            "img": "/img/cards/lev3_White_K7.png",
            "info": "",
            "yield": 1,
            "lv": 3,
            "score": 4,
            "price": [0, 0, 0, 0, 7]
        },
        {
            "id": 91,
            "code": "CD3W430036",
            "name": "Gioielleria",
            "img": "/img/cards/lev3_White_W3R3K6.png",
            "info": "",
            "yield": 1,
            "lv": 3,
            "score": 4,
            "price": [3, 0, 0, 3, 6]
        },
        {
            "id": 92,
            "code": "CD3W530007",
            "name": "building (white)",
            "img": "/img/cards/lev3_White_W3K7.png",
            "info": "",
            "yield": 1,
            "lv": 3,
            "score": 5,
            "price": [3, 0, 0, 0, 7]
        },
        {
            "id": 93,
            "code": "CD3G353033",
            "name": "timbered house",
            "img": "/img/cards/lev3_Green_W5B3R3K3.png",
            "info": "",
            "yield": 3,
            "lv": 3,
            "score": 3,
            "price": [5, 3, 0, 3, 3]
        },
        {
            "id": 94,
            "code": "CD3G407000",
            "name": "bridge",
            "img": "/img/cards/lev3_Green_B7.png",
            "info": "",
            "yield": 3,
            "lv": 3,
            "score": 4,
            "price": [0, 7, 0, 0, 0]
        },
        {
            "id": 95,
            "code": "CD3G436300",
            "name": "bridge",
            "img": "/img/cards/lev3_Green_W3B6G3.png",
            "info": "",
            "yield": 3,
            "lv": 3,
            "score": 4,
            "price": [3, 6, 3, 0, 0]
        },
        {
            "id": 96,
            "code": "CD3G507300",
            "name": "timbered house",
            "img": "/img/cards/lev3_Green_B7G3.png",
            "info": "",
            "yield": 3,
            "lv": 3,
            "score": 5,
            "price": [0, 7, 3, 0, 0]
        },
        {
            "id": 97,
            "code": "CD3R335303",
            "name": "equestrian statue",
            "img": "/img/cards/lev3_Red_W3B5G3K3.png",
            "info": "",
            "yield": 4,
            "lv": 3,
            "score": 3,
            "price": [3, 5, 3, 0, 3]
        },
        {
            "id": 98,
            "code": "CD3R400700",
            "name": "equestrian statue",
            "img": "/img/cards/lev3_Red_G7.png",
            "info": "",
            "yield": 4,
            "lv": 3,
            "score": 4,
            "price": [0, 0, 7, 0, 0]
        },
        {
            "id": 99,
            "code": "CD3R403630",
            "name": "building (red)",
            "img": "/img/cards/lev3_Red_B3G6R3.png",
            "info": "",
            "yield": 4,
            "lv": 3,
            "score": 4,
            "price": [0, 3, 6, 3, 0]
        },
        {
            "id": 100,
            "code": "CD3R500730",
            "name": "building (red)",
            "img": "/img/cards/lev3_Red_G7R3.png",
            "info": "",
            "yield": 4,
            "lv": 3,
            "score": 5,
            "price": [0, 0, 7, 3, 0]
        },
        {
            "id": 54,
            "code": "CD2K200530",
            "name": "lapidary (black)",
            "img": "/img/cards/lev2_Black_G5R3.png",
            "info": "",
            "yield": 5,
            "lv": 2,
            "score": 2,
            "price": [0, 0, 5, 3, 0]
        },
        {
            "id": 62,
            "code": "CD2B306000",
            "name": "lapidary (blue)",
            "img": "/img/cards/lev2_Blue_B6.png",
            "info": "",
            "yield": 2,
            "lv": 2,
            "score": 3,
            "price": [0, 6, 0, 0, 0]
        }
    ]);
    for (var i = 0, card; card = data[i]; i++) {
        comp.card[card.id] = card;
    }
    isReadPrevComp = true;
}